### ISSUE TITLE
The reference for the generation of M_dynamic matrix.

### ISSUE THREAD

**Issue by EthanCodesss** [ruiqini/NLC_ADMM-UAV#1]
Hello,

I am reaching out for some references or explanations regarding the calculation of the M_matrix within the function static Eigen::MatrixXd dynamic_matrix(). Specifically, I would appreciate it if you could provide insights into how the formula for this calculation is designed.

Could you please share any relevant documentation, research papers, or any other materials that detail the methodology behind the matrix computation?

Thank you very much for your time and assistance.

**Comment by ruiqini** [comment]
Thanks for your interest. The dynamic matrix comes from the famous minimum snap paper https://ieeexplore.ieee.org/document/5980409. For a polynomial path, we can compute its derivative with respect to its time parameter, and the fourth derivative is the snap term. In my code, N means the polynomial power order, and K means the derivative order.

**Comment by EthanCodesss** [comment]
> Thanks for your interest. The dynamic matrix comes from the famous minimum snap paper https://ieeexplore.ieee.org/document/5980409. For a polynomial path, we can compute its derivative with respect to its time parameter, and the fourth derivative is the snap term. In my code, N means the polynomial power order, and K means the derivative order.

Thank you very much for your timely response and assistance!

**Comment by EthanCodesss** [comment]
> Thanks for your interest. The dynamic matrix comes from the famous minimum snap paper https://ieeexplore.ieee.org/document/5980409. For a polynomial path, we can compute its derivative with respect to its time parameter, and the fourth derivative is the snap term. In my code, N means the polynomial power order, and K means the derivative order.

Hello, I have derived the dynamic matrix item in the code, but it is always inconsistent with what is used in the code. However, I don't know where the problem lies. Here is the code and my corresponding derivation process. How did you construct this matrix? Did I miss anything?

Thank you in advance!

```
double temp1=((k0+k1)%2==0) ? 1 : -1;

temp1*=combination[K][k0]*combination[K][k1]*combination[N-K][i-k0]*combination[N-K][j-k1]/(double)combination[2*N-K-K][i+j-k0-k1];
 for(int s=0;s<K;s++)
 {
 temp1*=(N-s)*(N-s);
 }

temp1/=(double)(2*N-K-K+1);
temp+=temp1;
```

This is my derivation process:
![image](https://github.com/ruiqini/traj-opt-admm/assets/67490630/86b9860c-039d-46e7-9e03-3e887406478f)
![image](https://github.com/ruiqini/traj-opt-admm/assets/67490630/f959cf59-bca2-4f0b-b646-b5468b0cd54e)
![image](https://github.com/ruiqini/traj-opt-admm/assets/67490630/38ddd3c1-c341-4a97-8d65-ffd717f517b8)
![image](https://github.com/ruiqini/traj-opt-admm/assets/67490630/b63ec719-5c61-4981-99d9-8bd819eee73b)
![image](https://github.com/ruiqini/traj-opt-admm/assets/67490630/30c11abc-b0be-4177-bd16-ce56a7473967)
